[package]
edition = "2021"
name = "links"
publish = false
version = "0.0.0"

[dependencies]
chrono = { version = "0.4.22", features = ["serde"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_yaml = "0.9.10"
url = { verison = "2.2.2", features = ["serde"] }
